### ISSUE TITLE
Medical mechanoid gets stuck in endless loop during emergency amputation

### ISSUE THREAD

**Issue by vonMort** [Dorely/EmergencySurgery#1]
Hello,

first of all, thank you very much for the great mod “Emergency Surgery”! I've discovered a problem when trying to use the medical mechanoid (built as a mechanitor) for emergency amputation of infected body parts. When the mechanoid performs the amputation, it gets into an infinite loop where it keeps trying to amputate the body part but can never successfully complete it.

*Steps to reproduction:*

1. equip Mechanitor with a medical mechanoid.
2. perform an emergency amputation on an infected body part of a colonist.
3. watch the mechanoid get stuck in an infinite loop and restart the process over and over again without completing it.

*Expected behavior:*

The mechanoid should perform the amputation correctly and complete the procedure successfully without getting stuck in an infinite loop.

*Actual behavior:*

The mechanoid gets stuck in an infinite loop and tries to restart the amputation procedure over and over again, resulting in an infinite process that never ends.

*Additional information:*

- Mod version: Update 4/11/2024
- RimWorld version: 1.5
- Other installed mods: Can be provided if relevant

I hope this information helps with troubleshooting. Many thanks in advance for your support!

Best regards

**Comment by Dorely** [comment]
Thanks! pushed a fix a few moments ago
